// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHJQ9QubxD78vrUxfRrDcGUNM_Kdl_JKE',
    appId: '1:657061738482:web:c53642c6da11ccbf80dd6b',
    messagingSenderId: '657061738482',
    projectId: 'moviesync-bdd7a',
    authDomain: 'moviesync-bdd7a.firebaseapp.com',
    storageBucket: 'moviesync-bdd7a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASP6jpOS4duiZjgdWQpt1YpGOXQ5Otam4',
    appId: '1:657061738482:android:4f77d4228b4aa6dc80dd6b',
    messagingSenderId: '657061738482',
    projectId: 'moviesync-bdd7a',
    storageBucket: 'moviesync-bdd7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCElYKJJNWdAroTfLynX-ujfolp2gGhEGI',
    appId: '1:657061738482:ios:8a5b3667acb8e53080dd6b',
    messagingSenderId: '657061738482',
    projectId: 'moviesync-bdd7a',
    storageBucket: 'moviesync-bdd7a.appspot.com',
    iosBundleId: 'com.example.moviesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCElYKJJNWdAroTfLynX-ujfolp2gGhEGI',
    appId: '1:657061738482:ios:99c6ed1d56dcc49a80dd6b',
    messagingSenderId: '657061738482',
    projectId: 'moviesync-bdd7a',
    storageBucket: 'moviesync-bdd7a.appspot.com',
    iosBundleId: 'com.example.moviesync.RunnerTests',
  );
}
